---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sign_up":
    post:
      summary: Sign up
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
        required: true
  "/sign_in":
    post:
      summary: Sign in
      security:
      - Bearer: {}
      responses:
        '200':
          description: sign in
  "/me":
    get:
      summary: Show current user
      security:
      - Bearer: {}
      responses:
        '200':
          description: get current user
    put:
      summary: Update user
      security:
      - Bearer: {}
      parameters: []
      responses:
        '204':
          description: update user info
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
    delete:
      summary: Delete current user
      security:
      - Bearer: {}
      responses:
        '204':
          description: delete current user
components:
  securitySchemes:
    Bearer:
      description: token
      type: apiKey
      name: Authorization
      in: header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
